config/routes.rb
Quikr::Application.routes.draw do
  resources :users

  resources :ad_posts

  resources :cities

  resources :categories

end

app/models/ad_post.rb
class AdPost < ActiveRecord::Base
  attr_accessible :description, :price, :title, :category_id, :city_id, :user_id

  validates :name, presence: true

  belongs_to :category

  belongs_to :city

  belongs_to :user
  
  accepts_nested_attributes_for :user
  
  
end

app/controllers/ad_posts_controller.rb
class AdPostsController < ApplicationController
  # GET /ad_posts
  # GET /ad_posts.json
  def index
    @ad_posts = AdPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ad_posts }
    end
  end

  # GET /ad_posts/1
  # GET /ad_posts/1.json
  def show
    @ad_post = AdPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad_post }
    end
  end

  # GET /ad_posts/new
  # GET /ad_posts/new.json
  def new
    @ad_post = AdPost.new
    @ad_post.users.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad_post }
    end
  end

  # GET /ad_posts/1/edit
  def edit
    @ad_post = AdPost.find(params[:id])
  end

  # POST /ad_posts
  # POST /ad_posts.json
  def create
    @ad_post = AdPost.new(params[:ad_post])

    respond_to do |format|
      if @ad_post.save
        format.html { redirect_to @ad_post, notice: 'Ad post was successfully created.' }
        format.json { render json: @ad_post, status: :created, location: @ad_post }
      else
        format.html { render action: "new" }
        format.json { render json: @ad_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ad_posts/1
  # PUT /ad_posts/1.json
  def update
    @ad_post = AdPost.find(params[:id])

    respond_to do |format|
      if @ad_post.update_attributes(params[:ad_post])
        format.html { redirect_to @ad_post, notice: 'Ad post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ad_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_posts/1
  # DELETE /ad_posts/1.json
  def destroy
    @ad_post = AdPost.find(params[:id])
    @ad_post.destroy

    respond_to do |format|
      format.html { redirect_to ad_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ad_posts_helper.rb
module AdPostsHelper
end

app/views/ad_posts/_form.html.erb
<%= form_for(@ad_post) do |f| %>
  <% if @ad_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_post.errors.count, "error") %> prohibited this ad_post from being saved:</h2>

      <ul>
      <% @ad_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">

    Category<br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {:prompt => "--Select Category--" })  %>
  </div>

  <div class="field">

    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">


    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">

    City<br />
    <%= f.collection_select(:city_id, City.all, :id, :name, {:prompt => "--Select City--"})  %>
  </div>
  <div class="field">

    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <% f.fields_for :users do |user| %>
    <div class="field">

   <div class="field">
  
   Name<br />
    <%= f.label :name %><br />
    <%= user.text_field :name %>
  </div>
  <div class="field">
  
    Email<br />
    <%= f.label :email %><br />
    <%= user.text_field :email %>
  </div>
  
  <div class="field">
    Phone<br />
    <%= f.label :phone %><br />
    <%= user.text_field :phone %>
  </div>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ad_posts/edit.html.erb
<h1>Editing Ad Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad_post %> |
<%= link_to 'Back', ad_posts_path %>

app/views/ad_posts/index.html.erb
<h1>All Ad_Posts</h1>

<table>

<% @ad_posts.each do |ad_post| %>
  <tr>
    <td><%= ad_post.title %></td>
    <td><%= ad_post.description %></td>
    <td><%= ad_post.price %></td>
    <td><%= link_to 'Show', ad_post %></td>
    <td><%= link_to 'Edit', edit_ad_post_path(ad_post) %></td>
    <td><%= link_to 'Destroy', ad_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ad post', new_ad_post_path %>

app/views/ad_posts/new.html.erb
<h1>New ad_post</h1>

<%= render 'form' %>

<%= link_to 'Back', ad_posts_path %>

app/views/ad_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @ad_post.title %>
</p>

<p>
  <b>Description:</b>
  <%= @ad_post.description %>
</p>

<p>
  <b>Price:</b>
  <%= @ad_post.price %>
</p>


<%= link_to 'Edit', edit_ad_post_path(@ad_post) %> |
<%= link_to 'Back', ad_posts_path %>